controller_manager:
  ros__parameters:
    update_rate: 100
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
      - rg2_finger_joint1
      
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    gains:
      shoulder_pan_joint:  {p: 500.0, i: 0.01, d: 10.0}
      shoulder_lift_joint: {p: 500.0, i: 0.01, d: 10.0}
      elbow_joint:         {p: 500.0, i: 0.01, d: 10.0}
      wrist_1_joint:       {p: 100.0, i: 0.01, d: 5.0}
      wrist_2_joint:       {p: 100.0, i: 0.01, d: 5.0}
      wrist_3_joint:       {p: 100.0, i: 0.01, d: 5.0}
      rg2_finger_joint1:   {p: 500.0,  i: 0.1, d: 5.0}

